### ISSUE TITLE
pypi package

### ISSUE THREAD

**Issue by davedash** [erans/ec2instancespricing#11]
It would be awesome if this were in pip.

Hynek wrote [a nice guide](hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/).

If I had some time, I'd do this in my fork.

Thanks for creating this.

**Comment by erans** [comment]
Someone contributed the code to make it work with pip so you can use:
pip install git+https://github.com/erans/ec2instancespricing

At some point (later) I will upload to it pypi.
