### ISSUE TITLE
Price differences with the pricing page

### ISSUE THREAD

**Issue by pablodo** [erans/ec2instancespricing#23]
I'm looking for the prices for `ondemand`, `us-east-1`, `linux`, `m3.2xlarge`. In the page, it says that the price is $0.560:

![image](https://cloud.githubusercontent.com/assets/1434199/5506516/d348843c-8779-11e4-85d6-a412b4f825e1.png)

But when I run the script like this:

`./ec2instancespricing.py --type ondemand --filter-region us-east-1 --filter-type 'm3.2xlarge' --filter-os-type 'linux' --format json`

The output is:

`{"regions": [{"region": "us-east-1", "instanceTypes": [{"os": "linux", "price": 0.9, "type": "m3.2xlarge"}]}], "config": {"currency": "USD", "unit": "perhr"}}`

I think the problem is that the API may be deprecated. If you make a request to http://aws.amazon.com/ec2/pricing/pricing-on-demand-instances.json, you will see that it redirects to a deprecated API.

**Comment by erans** [comment]
The code should be using the newer JSONs now so it should be ok. Give it a try.
