### ISSUE TITLE
Install via pip not working

### ISSUE THREAD

**Issue by timothyclemansspd** [erans/ec2instancespricing#37]
In [2]: import ec2instancespricing
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-c6f4106b3fd1> in <module>()
----> 1 import ec2instancespricing

/usr/local/lib/python2.7/dist-packages/ec2instancespricing/__init__.py in <module>()
----> 1 from ec2instancespricing.ec2instancespricing import get_prices

ImportError: No module named ec2instancespricing

**Comment by erans** [comment]
Are you trying to install via pip locally (i.e. "pip install .") ? If so, make sure you are not inside the internal ec2instancespricing directory.

**Comment by timothyclemansspd** [comment]
I did pip install [[ git url ]]

**Comment by erans** [comment]
Try this:
pip install git+https://github.com/erans/ec2instancespricing

**Comment by timothyclemansspd** [comment]
ubuntu@ip-172-31-15-173:~$ sudo pip install git+https://github.com/erans/ec2instancespricing
Downloading/unpacking git+https://github.com/erans/ec2instancespricing
  Cloning https://github.com/erans/ec2instancespricing to /tmp/pip-kEalXv-build
  Running setup.py (path:/tmp/pip-kEalXv-build/setup.py) egg_info for package from git+https://github.com/erans/ec2instancespricing

  Requirement already satisfied (use --upgrade to upgrade): ec2instancespricing==0.1 from git+https://github.com/erans/ec2instancespricing in /usr/local/lib/python2.7/dist-packages
Cleaning up...

**Comment by erans** [comment]
Great. You should have it now.

Go into Python and run:
```python
import ec2instancespricing
```

You will be able to call the methods from the module.

**Comment by timothyclemansspd** [comment]
IPython 2.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import ec2instancespricing
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c6f4106b3fd1> in <module>()
----> 1 import ec2instancespricing

/usr/local/lib/python2.7/dist-packages/ec2instancespricing/__init__.py in <module>()
----> 1 from ec2instancespricing.ec2instancespricing import get_prices

ImportError: No module named ec2instancespricing

**Comment by erans** [comment]
I found the problem. It seems the import path in the __init__.py file was working well for OSX but not Linux. I have fixed that for now for Linux.

Please run:
```bash
pip uninstall ec2instancespricing
```

and then run:
```bash
pip install git+https://github.com/erans/ec2instancespricing
```

It should work for you in Python (and IPython).

**Comment by timothyclemansspd** [comment]
It's working! Thank you.
