### ISSUE TITLE
No ap-south-1 in map JSON_NAME_TO_EC2_REGIONS_API

### ISSUE THREAD

**Issue by mapcuk** [erans/ec2instancespricing#45]
Traceback:
  File "./ec2instancespricing/ec2instancespricing.py", line 510, in get_ec2_instances_prices
    region_name = JSON_NAME_TO_EC2_REGIONS_API[r["region"]]
KeyError: u'ap-south-1'

Fixed by adding new entity to map
-    "ap-south-1": "ap-south-1",

**Comment by erans** [comment]
You can go ahead and send a pull request.
