### ISSUE TITLE
Generate instance type array programmatically?

### ISSUE THREAD

**Issue by QuinnyPig** [erans/ec2instancespricing#54]
If you're willing to pull in botocore, 
```python
import botocore.session

sess = botocore.session.Session()
available_types = sess.get_service_model('ec2').shape_for('InstanceType').enum
```
generates the instance type list at runtime; wouldn't be hard to work that in instead. 

How do you feel about that, philosophically?

**Comment by erans** [comment]
I would rather not depend on boto which is kind of a beast of a library just for that. Instance types are not added too frequently so its not that big of a deal.
