### ISSUE TITLE
How to run ec2instancespricing.py script

### ISSUE THREAD

**Issue by Wole72** [erans/ec2instancespricing#61]
I would like to how to run this script is there any specific parameter args I need to run the script right now im just using python ec2instancespricing.py. However I'm getting this error when running the scripts 

Traceback (most recent call last):
  File "ec2instancespricing.py", line 854, in <module>
    data, _ = _get_data(args)
  File "ec2instancespricing.py", line 801, in _get_data
    data = merge_instances(data, get_ec2_spot_instances_prices(args.filter_region, args.filter_type, args.filter_type_pattern, args.filter_os_type))
  File "ec2instancespricing.py", line 739, in get_ec2_spot_instances_prices
    result = get_ec2_instances_prices(urls, "spot", filter_region, filter_instance_type, filter_instance_type_pattern, filter_os_type, use_cache, cache_class)
  File "ec2instancespricing.py", line 544, in get_ec2_instances_prices
    region_name = JSON_NAME_TO_EC2_REGIONS_API[r["region"]]
KeyError: 'us-west-2-lax-1a'

**Comment by erans** [comment]
There were a few more regions added since the last time the script was
updated. I will add the zones shortly.

Eran

**Comment by erans** [comment]
added.
